In [1]:
# import pandas as pd 
import numpy as np
from doubleml.plm.pdml_data import panel_sim_CP

df = panel_sim_CP(seed=1)

# df_comp = pd.read_csv('dgp4_cre_short.csv')
# print(np.mean(df['x12'])) # print(np.mean(df_comp['x12']))

df.head(11)

id  time         d          y        x1        x2        x3        x4  \
0    1     1  5.688565   5.575328 -3.844683  0.127726 -1.787843 -0.652025   
1    1     2  1.803330   0.888238  3.624470 -1.802684 -0.562761  0.855777   
2    1     3  6.503023   7.930423  1.907997 -0.312405  3.099893  1.225655   
3    1     4  2.127946   1.944358 -1.331954 -0.691216  1.142492  3.825156   
4    1     5  3.623328   4.710092  0.879019 -4.078409  2.609659 -0.088702   
5    1     6  8.224220  11.243063  3.183299  2.021404  3.522853  2.698057   
6    1     7  0.537203  -0.312131  0.889688 -2.227148 -2.674028  5.603542   
7    1     8  1.054859   1.672320 -1.324784 -5.153931 -0.071145  0.251530   
8    1     9  1.639310   1.337860  0.161560  2.257953 -3.481427 -1.369462   
9    1    10  0.975663   1.928549 -0.039030  1.635466  2.134317  0.214096   
10   2     1 -3.601025  -4.280872  1.820927  1.745184 -3.273723 -0.345453   

          x5        x6  ...       x21       x22       x23       x24       x25  \
0  -0.579103  0.423272  ...  3.226371 -1.206765  0.287060  3.936408  2.161247   
1  -0.646218 -0.876128  ... -0.397198 -3.377483  2.261128 -3.301694 -0.320195   
2  -3.661449  8.851705  ...  1.744194 -1.407474 -2.489719 -0.150733  2.597059   
3   0.078136  3.251059  ...  0.754049  2.254103  1.755821 -1.486690 -4.349257   
4   1.980767  0.424544  ...  2.202419  2.395393 -2.453312  1.875244 -2.323682   
5  -0.632502 -0.595525  ... -4.237946  0.200640  0.917382  1.922730 -2.009517   
6   4.292786 -3.111922  ... -1.768282  2.736326 -0.132751  3.240039 -1.067903   
7   0.644162  3.349872  ...  2.160536  1.623199  7.426158 -1.342145 -0.848627   
8  -0.311600 -1.629059  ...  3.441772 -2.568581 -2.438071  3.801736  1.361282   
9   2.310866 -0.327077  ... -4.665311  0.809013  0.952386  0.109747  2.464676   
10 -0.206685 -0.531905  ...  0.795408  1.899734 -0.273145 -1.522430 -2.387845   

         x26       x27       x28       x29       x30  
0   1.594426  2.920766 -1.351933  1.423444  3.151186  
1   2.309822 -0.497333  3.287378 -1.945398  0.825535  
2  -0.061558  3.905148 -1.733110  0.316718 -5.626626  
3  -2.046951  2.739532 -2.355801  1.824729 -1.369384  
4   1.639090 -4.245873 -2.497935 -1.138097 -0.372274  
5   0.714775  0.711414 -0.043003  0.335447  1.036494  
6   0.058138 -3.015777  2.912558 -0.810825 -3.320911  
7  -2.269170  0.974895 -1.537269 -6.033720 -2.713107  
8  -4.206963  1.111928  0.530692 -4.795123 -0.826367  
9  -2.749412  2.478942 -1.571778  1.622380 -0.724943  
10 -0.171460  1.281184  1.024001 -0.039841 -1.341951  

[11 rows x 34 columns]

Random splitting

In [2]:
from sklearn.model_selection import RepeatedKFold

n_obs = df.shape[0]
n_folds = 5

np.random.seed(1)
resampling = RepeatedKFold(n_splits=n_folds, n_repeats=1)

all_smpls = [(train, test) for train, test in resampling.split(X=np.zeros(n_obs), y=None, groups=None)]
smpls = [all_smpls]

smpls[0][0]


(array([   0,    1,    2, ..., 2493, 2494, 2495], shape=(2000,)),
 array([   4,    6,   17,   30,   40,   47,   50,   54,   56,   58,   65,
          75,   81,   93,  102,  107,  108,  111,  119,  120,  124,  126,
         130,  134,  165,  169,  171,  177,  192,  194,  195,  203,  205,
         206,  208,  216,  219,  228,  231,  236,  241,  242,  255,  258,
         270,  275,  280,  282,  285,  287,  292,  297,  304,  306,  314,
         321,  329,  335,  340,  346,  348,  366,  367,  368,  370,  396,
         397,  403,  415,  425,  428,  432,  438,  439,  440,  442,  443,
         444,  453,  464,  468,  477,  480,  481,  485,  486,  487,  495,
         499,  508,  514,  517,  521,  525,  527,  535,  540,  544,  546,
         547,  553,  555,  557,  559,  560,  561,  563,  569,  572,  586,
         587,  589,  592,  598,  607,  610,  612,  613,  614,  620,  623,
         632,  638,  642,  655,  660,  664,  671,  674,  675,  679,  685,
         692,  693,  703,  707,  708,  712,  7

In [3]:
from doubleml.utils.resampling import DoubleMLClusterResampling

np.random.seed(1)
obj_dml_resampling = DoubleMLClusterResampling(n_folds=5,
                                               n_rep=1,
                                               n_obs=df.shape[0],
                                               n_cluster_vars=1,
                                               cluster_vars=df['id'].values.reshape((-1,1))
                                               )

smpls, smpls_cluster = obj_dml_resampling.split_samples()

smpls[0][0][0]


array([  10,   11,   12, ..., 2487, 2488, 2489], shape=(2000,))

Sample splitting by unit or time, using GroupKFold, only 1 repeat like this

In [4]:
from sklearn.model_selection import GroupKFold

groups = list(df['id']) # 'time'

gkf = GroupKFold(n_splits=5)

all_smpls = [(train, test) for train, test in gkf.split(X=np.zeros(df.shape[0]), y=None, groups=groups)]
smpls = [all_smpls]

print(len(smpls[0][4][1]))
smpls[0][4][1][:50] # df indices inlcudes all periods for 1 unit

500


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [5]:
from doubleml.plm.pdml_resampling import DoubleMLPanelResampling

obj_pdml_resampling = DoubleMLPanelResampling(n_folds=5,
                                             n_obs=df.shape[0],
                                             method='by_group',
                                             groups=list(df['id'])
                                             )

smpls = obj_pdml_resampling.split_samples()

smpls[0][4][1][:50]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [6]:
groups = list(df['time']) 

gkf = GroupKFold(n_splits=5)

all_smpls = [(train, test) for train, test in gkf.split(X=np.zeros(df.shape[0]), y=None, groups=groups)]
smpls = [all_smpls]

print(len(smpls[0][4][1]))
smpls[0][4][1][:50]
# smpls[0][4][0][:50]

500


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245])

In [7]:
from doubleml.plm.pdml_resampling import DoubleMLPanelResampling

obj_pdml_resampling = DoubleMLPanelResampling(n_folds=5,
                                             n_obs=df.shape[0],
                                             method='by_group',
                                             groups=list(df['time'])
                                             )

smpls = obj_pdml_resampling.split_samples()

smpls[0][4][1][:50]

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245])

Splitting by time into folds with adjacent periods, no repeated cross-fitting possible

In [19]:
from sklearn.model_selection import GroupKFold

n_folds = 10 # 5

resampling = GroupKFold(n_splits=n_folds)

all_smpls = []
all_smpls_time = []

smpls_time_var = []
time_var = df['time'].values # .sort_values(ascending=False), reshape
time_periods = np.unique(time_var)
print(time_periods)
n_time_periods = len(time_periods)

time_periods_per_fold = len(time_periods) // n_folds

group = np.repeat(np.arange(n_folds), time_periods_per_fold)
print(group)

smpls_time_var.append([(time_periods[train], time_periods[test])
                            for train, test in resampling.split(np.zeros(n_time_periods), groups=group)])

from copy import deepcopy

smpls_time_var_d = deepcopy(smpls_time_var)
smpls_time_var

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


[[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10])),
  (array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]), array([9])),
  (array([ 1,  2,  3,  4,  5,  6,  7,  9, 10]), array([8])),
  (array([ 1,  2,  3,  4,  5,  6,  8,  9, 10]), array([7])),
  (array([ 1,  2,  3,  4,  5,  7,  8,  9, 10]), array([6])),
  (array([ 1,  2,  3,  4,  6,  7,  8,  9, 10]), array([5])),
  (array([ 1,  2,  3,  5,  6,  7,  8,  9, 10]), array([4])),
  (array([ 1,  2,  4,  5,  6,  7,  8,  9, 10]), array([3])),
  (array([ 1,  3,  4,  5,  6,  7,  8,  9, 10]), array([2])),
  (array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]), array([1]))]]

In [20]:
len(smpls_time_var[0][0])
np.sum(np.isin(df['time'], smpls_time_var[0][1][0]))

np.int64(2250)

In [21]:
n_obs = df.shape[0]

all_smpls = []
all_smpls_timefold = []
smpls = []
smpls_timefold = []

for i_smpl in range(n_folds):
    ind_train = np.full(n_obs, True)
    ind_test = np.full(n_obs, True)
    this_timefold_smpl_train = []
    this_timefold_smpl_test = []

    train_timefolds = smpls_time_var[0][i_smpl][0]
    test_timefolds = smpls_time_var[0][i_smpl][1]
    this_timefold_smpl_train.append(train_timefolds)
    this_timefold_smpl_test.append(test_timefolds)
    ind_train = ind_train & np.isin(time_var, train_timefolds)
    ind_test = ind_test & np.isin(time_var, test_timefolds)
    
    train_set = np.arange(n_obs)[ind_train]
    test_set = np.arange(n_obs)[ind_test]
    smpls.append((train_set, test_set))
    smpls_timefold.append((this_timefold_smpl_train, this_timefold_smpl_test))
all_smpls.append(smpls)
all_smpls_timefold.append(smpls_timefold)

print(len(all_smpls[0][0][0]))
all_smpls[0][0][1]#[:50]

2250


array([   9,   19,   29,   39,   49,   59,   69,   79,   89,   99,  109,
        119,  129,  139,  149,  159,  169,  179,  189,  199,  209,  219,
        229,  239,  249,  259,  269,  279,  289,  299,  309,  319,  329,
        339,  349,  359,  369,  379,  389,  399,  409,  419,  429,  439,
        449,  459,  469,  479,  489,  499,  509,  519,  529,  539,  549,
        559,  569,  579,  589,  599,  609,  619,  629,  639,  649,  659,
        669,  679,  689,  699,  709,  719,  729,  739,  749,  759,  769,
        779,  789,  799,  809,  819,  829,  839,  849,  859,  869,  879,
        889,  899,  909,  919,  929,  939,  949,  959,  969,  979,  989,
        999, 1009, 1019, 1029, 1039, 1049, 1059, 1069, 1079, 1089, 1099,
       1109, 1119, 1129, 1139, 1149, 1159, 1169, 1179, 1189, 1199, 1209,
       1219, 1229, 1239, 1249, 1259, 1269, 1279, 1289, 1299, 1309, 1319,
       1329, 1339, 1349, 1359, 1369, 1379, 1389, 1399, 1409, 1419, 1429,
       1439, 1449, 1459, 1469, 1479, 1489, 1499, 15

In [22]:
from doubleml.plm.pdml_resampling import DoubleMLPanelResampling

obj_pdml_resampling = DoubleMLPanelResampling(n_folds=10,
                                             n_obs=df.shape[0],
                                             method='time_folds',
                                             groups=list(df['time'])
                                             )

smpls = obj_pdml_resampling.split_samples()

print(len(smpls[0][0][0]))
smpls[0][0][1]

2250


array([   9,   19,   29,   39,   49,   59,   69,   79,   89,   99,  109,
        119,  129,  139,  149,  159,  169,  179,  189,  199,  209,  219,
        229,  239,  249,  259,  269,  279,  289,  299,  309,  319,  329,
        339,  349,  359,  369,  379,  389,  399,  409,  419,  429,  439,
        449,  459,  469,  479,  489,  499,  509,  519,  529,  539,  549,
        559,  569,  579,  589,  599,  609,  619,  629,  639,  649,  659,
        669,  679,  689,  699,  709,  719,  729,  739,  749,  759,  769,
        779,  789,  799,  809,  819,  829,  839,  849,  859,  869,  879,
        889,  899,  909,  919,  929,  939,  949,  959,  969,  979,  989,
        999, 1009, 1019, 1029, 1039, 1049, 1059, 1069, 1079, 1089, 1099,
       1109, 1119, 1129, 1139, 1149, 1159, 1169, 1179, 1189, 1199, 1209,
       1219, 1229, 1239, 1249, 1259, 1269, 1279, 1289, 1299, 1309, 1319,
       1329, 1339, 1349, 1359, 1369, 1379, 1389, 1399, 1409, 1419, 1429,
       1439, 1449, 1459, 1469, 1479, 1489, 1499, 15

Neighbors-left-out cross-fitting

In [23]:
smpls_time_var_d

[[(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10])),
  (array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]), array([9])),
  (array([ 1,  2,  3,  4,  5,  6,  7,  9, 10]), array([8])),
  (array([ 1,  2,  3,  4,  5,  6,  8,  9, 10]), array([7])),
  (array([ 1,  2,  3,  4,  5,  7,  8,  9, 10]), array([6])),
  (array([ 1,  2,  3,  4,  6,  7,  8,  9, 10]), array([5])),
  (array([ 1,  2,  3,  5,  6,  7,  8,  9, 10]), array([4])),
  (array([ 1,  2,  4,  5,  6,  7,  8,  9, 10]), array([3])),
  (array([ 1,  3,  4,  5,  6,  7,  8,  9, 10]), array([2])),
  (array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]), array([1]))]]

In [28]:
for i in range(n_folds):
    train_up = smpls_time_var_d[0][i][0]
    smpls_time_var_d[0][i] = train_up[~np.isin(train_up, [smpls_time_var_d[0][i][1] - time_periods_per_fold,
                                                         smpls_time_var_d[0][i][1] + time_periods_per_fold])], smpls_time_var_d[0][i][1]

smpls_time_var_d

[[(array([1, 2, 3, 4, 5, 6, 7, 8]), array([10])),
  (array([1, 2, 3, 4, 5, 6, 7]), array([9])),
  (array([ 1,  2,  3,  4,  5,  6, 10]), array([8])),
  (array([ 1,  2,  3,  4,  5,  9, 10]), array([7])),
  (array([ 1,  2,  3,  4,  8,  9, 10]), array([6])),
  (array([ 1,  2,  3,  7,  8,  9, 10]), array([5])),
  (array([ 1,  2,  6,  7,  8,  9, 10]), array([4])),
  (array([ 1,  5,  6,  7,  8,  9, 10]), array([3])),
  (array([ 4,  5,  6,  7,  8,  9, 10]), array([2])),
  (array([ 3,  4,  5,  6,  7,  8,  9, 10]), array([1]))]]

In [32]:
# smpls_time_var_d

all_smpls = []
all_smpls_timefold = []
smpls = []
smpls_timefold = []

for i_smpl in range(n_folds):
    ind_train = np.full(n_obs, True)
    ind_test = np.full(n_obs, True)
    this_timefold_smpl_train = []
    this_timefold_smpl_test = []

    train_timefolds = smpls_time_var_d[0][i_smpl][0]
    test_timefolds = smpls_time_var_d[0][i_smpl][1]
    this_timefold_smpl_train.append(train_timefolds)
    this_timefold_smpl_test.append(test_timefolds)
    ind_train = ind_train & np.isin(time_var, train_timefolds)
    ind_test = ind_test & np.isin(time_var, test_timefolds)
    
    train_set = np.arange(n_obs)[ind_train]
    test_set = np.arange(n_obs)[ind_test]
    smpls.append((train_set, test_set))
    smpls_timefold.append((this_timefold_smpl_train, this_timefold_smpl_test))
all_smpls.append(smpls)
all_smpls_timefold.append(smpls_timefold)

print(len(all_smpls[0][5][0]))
all_smpls[0][1][0]

1750


array([   0,    1,    2, ..., 2494, 2495, 2496], shape=(1750,))

In [33]:
from doubleml.plm.pdml_resampling import DoubleMLPanelResampling

obj_pdml_resampling = DoubleMLPanelResampling(n_folds=10,
                                             n_obs=df.shape[0],
                                             method='time_folds_neighbors',
                                             groups=list(df['time'])
                                             )

smpls = obj_pdml_resampling.split_samples()

print(len(smpls[0][5][0]))
smpls[0][1][0]

1750


array([   0,    1,    2, ..., 2494, 2495, 2496], shape=(1750,))